% Create a yagiUda antenna
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 31-Oct-2019 21:23:44

%% Antenna Properties 
% Design antenna at frequency 146000000Hz
antennaObject = design(yagiUda,146000000);
% Properties changed 
antennaObject.DirectorSpacing = 0.254;
antennaObject.ReflectorSpacing = 0.47597;
antennaObject.DirectorLength = 0.9144;
antennaObject.ReflectorLength = 1.0287;
antennaObject.NumDirectors = 2;
% Update load properties 
antennaObject.Load.Impedance = 50;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 145000000;
% Define frequency range 
freqRange = (131.4:1.46:160.6) * 1e6;
% show for yagiUda
figure;
show(antennaObject) 
% current for yagiUda
figure;
current(antennaObject, plotFrequency) 
% pattern for yagiUda
figure;
pattern(antennaObject, plotFrequency) 
% azimuth for yagiUda
figure;
patternAzimuth(antennaObject, plotFrequency) 
% elevation for yagiUda
figure;
patternElevation(antennaObject, plotFrequency) 
% s11 for yagiUda
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 
% impedance for yagiUda
figure;
impedance(antennaObject, freqRange) 

